const BookInfo = [
    {
        id: 1,
        title: 'All the Light We Cannot See',
        author: 'Anthony Doerr',
        price: 14.99,        
        category: 'General Fiction',
    
    },
    {
        id: 2,
        title: 'The Candy House',
        author: 'Jennifer Egan',
        price: 17.99,        
        category: 'General Fiction',
    },
    {
        id: 3,
        title: 'Americanah',
        author: 'Chimamanda Ngozi Adichie',
        price: 16.95,        
        category: 'General Fiction',
    },
    {
        id: 4,
        title: 'The Wind-Up Bird Chronicle',
        author: 'Haruki Murakami',
        price: 17.99,        
        category: 'General Fiction',
    },
    {
        id: 5,
        title: 'The Brief Wondrous Life of Oscar Wao',
        author: 'Junot Díaz',
        price: 14.99,        
        category: 'General Fiction',
    },
    {
        id: 6,
        title: 'Little Fires Everywhere',
        author: 'Celeste Ng',
        price: 13.99,        
        category: 'General Fiction',
    },
    {
        id: 7,
        title: 'White Teeth',
        author: 'Zadie Smith',
        price: 14.99,        
        category: 'General Fiction',
    },
    {
        id: 8,
        title: 'Where the Crawdads Sing',
        author: 'Delia Owens',
        price: 13.49,        
        category: 'General Fiction',
    },
    {
        id: 9,
        title: 'The Goldfinch',
        author: 'Donna Tartt',
        price: 17.99,        
        category: 'General Fiction',
    },
    {
        id: 10,
        title: 'Salvage the Bones ',
        author: 'Jesmyn Ward',
        price: 14.99,        
        category: 'General Fiction',
    },
    {
        id:11,                             
        title: 'Blood of Elves',
        author: "Andrzej Sapkowski ",
        price: 17.99,                               
        category: 'Sci-Fi',
    },
    {
        id: 12,
        title: 'Escape Pod: The Science Fiction Anthology',
        author: "S.B. Divya, Mur Lafferty, N. K. Jemisin, Cory Doctorow, Ken Liu ",
        price: 15.95, 
        category: 'Sci-Fi',
    },
    {
        id: 13,
        title: 'The Best Science Fiction and Fantasy of the Year, Volume Eleven',
        author: "Joe Abercrombie, Jonathan Strahan, Geoff Ryman, Lavie Tidhar, Paolo Bacigalupi",
        price: 7.49, 
        category: 'Sci-Fi',
    },
    {
        id: 14,
        title: 'Lightspeed',
        author: "John Joseph Adams, N. K. Jemisin, Kij Johnson, Alexander Weinstein, Ramez Naam ",
        price: 3.99,
        category: 'Sci-Fi',
    },
    {
        id: 15,
        title: 'Clarkesworld: Year Eight',   
        author: "Neil Clarke, Michael Swanwick, N. K. Jemisin, Sean Wallace, Naomi Kritzer ",
        price: 6.99, 
        category: 'Sci-Fi',
    },
    {
        id: 16,
        title: "The Eye of the World",
        author: "Robert Jordan",
        price: 15.99,                               
        category: 'Sci-Fi',
    },
    {
        id: 17,
        title: "Abaddon's Gate",
        author: "James S. A. Corey",
        price: 15.99, 
        category: 'Sci-Fi',
    },
    {
        id: 18,
        title: "Mass Effect Andromeda: Initiation",
        author: "N. K. Jemisin, Mac Walters",
        price: 7.99, 
        category: 'Sci-Fi',   
    },
    {
        id: 19,
        title: "The City Born Great",
        author: "N. K. Jemisin",
        price: 1.99,  
        category: 'Sci-Fi',
    },
    {
        id: 20,
        title: "The Witcher",
        author: "Paul Tobin, Joe Querio",
        price: 1.99, 
        category: 'Sci-Fi',
    },
    {
        id: 21,                            
        title:'Snacking Cakes: Simple Treats for Anytime Cravings',                                
        author:"Yossy Arefi ",
        price: 22.99, 
        category:'Cookbook',
    },
    {
        id: 22, 
        title:'Mooncakes and Milk Bread: Sweet and Savory Recipes Inspired by Chinese Bakeries',
        author:"Kristina Cho ",
        price: 26.95, 
        category:'Cookbook',
    },
    {
        id: 23,
        title:'Flour Water Salt Yeast: The Fundamentals of Artisan Bread and Pizza',
        author:"Ken Forkish",
        price: 31.49, 
        category:'Cookbook',
    },
    {
        id: 24,
        title:'Paleo Baking at Home: The Ultimate Resource for Delicious Grain-Free Cookies and More',
        author:"Michele Rosen",
        price:19.79, 
        category:'Cookbook',
    },
    {
        id: 25,
        title:'The Great British Baking Show: Love to Bake',   
        author:"Paul Hollywood, Prue Leith ",
        price: 26.00, 
        category:'Cookbook',
    },
    {
        id: 26,
        title:"The Cook's Illustrated Baking Book",
        author:"America's Test Kitchen",
        price: 40.00,                                
        category:'Cookbook',
    },
    {
        id: 27,
        title:'Pieometry: Modern Tart Art and Pie Design for the Eye and the Palate',
        Author:"Lauren Ko",
        price: 32.50, 
        category:'Cookbook',
    },
    {
        id: 28,
        title:'French Pastry Made Simple: Foolproof Recipes for Éclairs, Tarts, Macarons and More',
        author:"Molly Wilkinsonv",
        price: 20.69, 
        category:'Cookbook',
    },
    {
        id: 29,
        title:'Grandbaby Cakes: Modern Recipes, Vintage Charm, Soulful Memories',
        author:"Jocelyn Delk Adams",
        price: 24.95,
        category:'Cookbook',
    },
    {
        id: 30,
        title:'Afternoon Tea At Home: Deliciously indulgent recipes for sandwiches, savouries, scones, cakes and other fancies',
        author:"Will Torrent",
        price: 27.99, 
        category:'Cookbook', 
    },
];

export default BookInfo;